apiVersion: v1
kind: Namespace
metadata:
  name: valkey-test
---
# Pod on AZ-a
apiVersion: v1
kind: Pod
metadata:
  name: glide-test-az-a
  namespace: valkey-test
  labels:
    app: glide-test
    az: ap-northeast-2a
spec:
  nodeSelector:
    topology.kubernetes.io/zone: ap-northeast-2a
  containers:
    - name: glide-test
      image: 533267203088.dkr.ecr.ap-northeast-2.amazonaws.com/valkey-glide-test:latest
      env:
        - name: VALKEY_ENDPOINT
          value: "clustercfg.vavoam29irgr1px.ykersa.apn2.cache.amazonaws.com"
        - name: VALKEY_PORT
          value: "6379"
        - name: AZ
          value: "ap-northeast-2a"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  restartPolicy: Never
---
# Pod on AZ-b
apiVersion: v1
kind: Pod
metadata:
  name: glide-test-az-b
  namespace: valkey-test
  labels:
    app: glide-test
    az: ap-northeast-2b
spec:
  nodeSelector:
    topology.kubernetes.io/zone: ap-northeast-2b
  containers:
    - name: glide-test
      image: 533267203088.dkr.ecr.ap-northeast-2.amazonaws.com/valkey-glide-test:latest
      env:
        - name: VALKEY_ENDPOINT
          value: "clustercfg.vavoam29irgr1px.ykersa.apn2.cache.amazonaws.com"
        - name: VALKEY_PORT
          value: "6379"
        - name: AZ
          value: "ap-northeast-2b"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  restartPolicy: Never
